export const CREATE_TEST_REQUEST = "CREATE_TEST_REQUEST";
export const CREATE_TEST_ERROR = "CREATE_TEST_ERROR";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";

export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_ERROR = "GET_TEST_ERROR";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";

export const GET_SINGLE_TEST_REQUEST = "GET_SINGLE_TEST_REQUEST";
export const GET_SINGLE_TEST_ERROR = "GET_SINGLE_TEST_ERROR";
export const GET_SINGLE_TEST_SUCCESS = "GET_SINGLE_TEST_SUCCESS";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_ERROR = "DELETE_TEST_ERROR";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
