export const SAVE_TEST_RESULT = "SAVE_TEST_RESULT";
export const GET_TEST_RESULT = "GET_TEST_RESULT";

export const GET_TEST_RESULT_REQUEST = "GET_TEST_RESULT_REQUEST";

export const SAVE_TEST_RESULT_ERROR = "SAVE_TEST_RESULT_ERROR";

export const GET_TEST_RESULT_ERROR = "GET_TEST_RESULT_ERROR";