export const CREATE_LESSON_REQUEST = "CREATE_LESSON_REQUEST";
export const CREATE_LESSON_ERROR = "CREATE_LESSON_ERROR";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";

export const GET_LESSON_REQUEST = "GET_LESSON_REQUEST";
export const GET_LESSON_ERROR = "GET_LESSON_ERROR";
export const GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS";

export const DELETE_LESSON_REQUEST = "DELETE_LESSON_REQUEST";
export const DELETE_LESSON_ERROR = "DELETE_LESSON_ERROR";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";

export const RESOLVE_LESSON_REQUEST = "RESOLVE_LESSON_REQUEST";
export const RESOLVE_LESSON_ERROR = "RESOLVE_LESSON_ERROR";
export const RESOLVE_LESSON_SUCCESS = "RESOLVE_LESSON_SUCCESS";
