export const CREATE_LESSONX_REQUEST = "CREATE_LESSONX_REQUEST";
export const CREATE_LESSONX_ERROR = "CREATE_LESSONX_ERROR";
export const CREATE_LESSONX_SUCCESS = "CREATE_LESSONX_SUCCESS";

export const GET_LESSONX_REQUEST = "GET_LESSONX_REQUEST";
export const GET_LESSONX_ERROR = "GET_LESSONX_ERROR";
export const GET_LESSONX_SUCCESS = "GET_LESSONX_SUCCESS";

export const DELETE_LESSONX_REQUEST = "DELETE_LESSONX_REQUEST";
export const DELETE_LESSONX_ERROR = "DELETE_LESSONX_ERROR";
export const DELETE_LESSONX_SUCCESS = "DELETE_LESSONX_SUCCESS";

