export const CREATE_ASSIGNMENT_REQUEST = "CREATE_ASSIGNMENT_REQUEST";
export const CREATE_ASSIGNMENT_ERROR = "CREATE_ASSIGNMENT_ERROR";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_ASSIGNMENT_REQUEST = "GET_ASSIGNMENT_REQUEST";
export const GET_ASSIGNMENT_ERROR = "GET_ASSIGNMENT_ERROR";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";

export const GET_SINGLE_ASSIGNMENT_REQUEST = "GET_SINGLE_ASSIGNMENT_REQUEST";
export const GET_SINGLE_ASSIGNMENT_ERROR = "GET_SINGLE_ASSIGNMENT_ERROR";
export const GET_SINGLE_ASSIGNMENT_SUCCESS = "GET_SINGLE_ASSIGNMENT_SUCCESS";

export const DELETE_ASSIGNMENT_REQUEST = "DELETE_ASSIGNMENT_REQUEST";
export const DELETE_ASSIGNMENT_ERROR = "DELETE_ASSIGNMENT_ERROR";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
