export const CREATE_DOUBTZ_REQUEST = "CREATE_DOUBTZ_REQUEST";
export const CREATE_DOUBTZ_ERROR = "CREATE_DOUBTZ_ERROR";
export const CREATE_DOUBTZ_SUCCESS = "CREATE_DOUBTZ_SUCCESS";

export const GET_DOUBTZ_REQUEST = "GET_DOUBTZ_REQUEST";
export const GET_DOUBTZ_ERROR = "GET_DOUBTZ_ERROR";
export const GET_DOUBTZ_SUCCESS = "GET_DOUBTZ_SUCCESS";

export const GET_SINGLE_DOUBTZ_REQUEST = "GET_SINGLE_DOUBTZ_REQUEST";
export const GET_SINGLE_DOUBTZ_ERROR = "GET_SINGLE_DOUBTZ_ERROR";
export const GET_SINGLE_DOUBTZ_SUCCESS = "GET_SINGLE_DOUBTZ_SUCCESS";

export const DELETE_DOUBTZ_REQUEST = "DELETE_DOUBTZ_REQUEST";
export const DELETE_DOUBTZ_ERROR = "DELETE_DOUBTZ_ERROR";
export const DELETE_DOUBTZ_SUCCESS = "DELETE_DOUBTZ_SUCCESS";

export const RESOLVE_DOUBTZ_REQUEST = "RESOLVE_DOUBTZ_REQUEST";
export const RESOLVE_DOUBTZ_ERROR = "RESOLVE_DOUBTZ_ERROR";
export const RESOLVE_DOUBTZ_SUCCESS = "RESOLVE_DOUBTZ_SUCCESS";

export const ADD_DOUBTZ_RESPONSE_REQUEST = "ADD_DOUBTZ_RESPONSE_REQUEST";
export const ADD_DOUBTZ_RESPONSE_ERROR = "ADD_DOUBTZ_RESPONSE_ERROR";
export const ADD_DOUBTZ_RESPONSE_SUCCESS = "ADD_DOUBTZ_RESPONSE_SUCCESS";
