export const CREATE_DOUBTX_REQUEST = "CREATE_DOUBTX_REQUEST";
export const CREATE_DOUBTX_ERROR = "CREATE_DOUBTX_ERROR";
export const CREATE_DOUBTX_SUCCESS = "CREATE_DOUBTX_SUCCESS";

export const GET_DOUBTX_REQUEST = "GET_DOUBTX_REQUEST";
export const GET_DOUBTX_ERROR = "GET_DOUBTX_ERROR";
export const GET_DOUBTX_SUCCESS = "GET_DOUBTX_SUCCESS";

export const GET_SINGLE_DOUBTX_REQUEST = "GET_SINGLE_DOUBTX_REQUEST";
export const GET_SINGLE_DOUBTX_ERROR = "GET_SINGLE_DOUBTX_ERROR";
export const GET_SINGLE_DOUBTX_SUCCESS = "GET_SINGLE_DOUBTX_SUCCESS";

export const DELETE_DOUBTX_REQUEST = "DELETE_DOUBTX_REQUEST";
export const DELETE_DOUBTX_ERROR = "DELETE_DOUBTX_ERROR";
export const DELETE_DOUBTX_SUCCESS = "DELETE_DOUBTX_SUCCESS";

export const RESOLVE_DOUBTX_REQUEST = "RESOLVE_DOUBTX_REQUEST";
export const RESOLVE_DOUBTX_ERROR = "RESOLVE_DOUBTX_ERROR";
export const RESOLVE_DOUBTX_SUCCESS = "RESOLVE_DOUBTX_SUCCESS";

export const ADD_DOUBTX_RESPONSE_REQUEST = "ADD_DOUBTX_RESPONSE_REQUEST";
export const ADD_DOUBTX_RESPONSE_ERROR = "ADD_DOUBTX_RESPONSE_ERROR";
export const ADD_DOUBTX_RESPONSE_SUCCESS = "ADD_DOUBTX_RESPONSE_SUCCESS";
